### PR TITLE
Added responsivity to pages

### PR DESCRIPTION
**Pull request by SuspenseFallback**
## Describe the changes

- Fix https://github.com/DCIS-Change-Makers-23-24/Internal/issues/29 for home page
- Fix https://github.com/DCIS-Change-Makers-23-24/Internal/issues/30 for home page

## Possible conflicts

None.

## Any other comments

Jaeden, I need you to review this extensively before you push to make sure it's completely responsive.

Also, check this out: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### CODE REVIEW

**Comment by Jaeden-T** [comment]
Don't name PRs as 'task' should only be a PR name or draft

Edited: title for fix with format

**Review by Jaeden-T — APPROVED** [review]

**Review by Jaeden-T — CHANGES_REQUESTED** [review]
Follow pull request format:
https://github.com/DCIS-Change-Makers-23-24/Internal

**Comment by SuspenseFallback** [comment]
[UPDATE] Alright, I have updated the pull request.

**Comment by Jaeden-T** [comment]
> [UPDATE] Alright, I have updated the pull request.
> 
> For clarification, when we make pull requests from a fork, should we merge it into `main`? Or is main the production branch, and we should merge into `dev` or another branch?

Alright from now on (after this PR_.

Do it

Fork --> dev --> Main.
Fork -->Dev should be just features
Dev --> main is when a bunch of features are done and its safe to deploy

**Comment by Jaeden-T** [comment]
Test cases: 

Ipad
image
image



Samsung phone:
image
image
image

**Comment by SuspenseFallback** [comment]
The original title was `Added responsivity to home page`: This PR was only for the home page
If you want, I can add the other changes here too

**Comment by Jaeden-T** [comment]
> The original title was `Added responsivity to home page`: This PR was only for the home page If you want, I can add the other changes here too

Fair point - roll it out in the next PR on new format then

**Pull request merged**
